begin
  require "jeweler"
  Jeweler::Tasks.new do |gem|
    gem.name = "meatloaf-core"
    gem.summary = "Test Framework Engine for Rails 3"
    gem.files = Dir["{lib}/**/*", "{app}/**/*", "{config}/**/*"]
    # other fields that would normally go in your gemspec
    # like authors, email and has_rdoc can also be included here
    gem.version = "0.0.1"      
    gem.add_dependency 'inherited_resources', '>= 1.1.2'
  end
rescue
  puts "Jeweler or one of its dependencies is not installed."
end